language: csharp
solution: CameraRecord.sln
install:
- nuget restore CameraRecord.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release CameraRecord.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CameraRecordTest/bin/Debug/CameraRecordTest.dll
